# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title:               Akshay Thorve
#tagline:             'foo's website
description:         Akshay's blog...
url: https://akshaythorve.com
baseurl: ""
urlimg: https://akshaythorve.com/images/
## If you do not have custom domain, comment top three lines, uncomment three lines below and replace dyndna with your github userid and lanyon-plus with your project name. Also, rename CNAME file to CNAME.sample
#url: https://dyndna.github.io/lanyon-plus
#baseurl: "/lanyon-plus"
#urlimg: https://dyndna.github.io/lanyon-plus/images/
markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
#timezone:    America/Chicago
future:      true


## code highlight options
syntax_highlighter: rouge
input: GFM

plugins:
  - github-pages
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "public/dormant"]

# About/contact
author:
  name:              Akshay Thorve
  url:               https://twitter.com/thorveakshay
  avatar:         foo.png
  #email:

# Owner/author information
owner:
  name:           Akshay Thorve
  avatar:         foo.png
  #email:
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        thorveakshay
  facebook:       akshaythorve
  github:         thorveakshay
  stackexchange:
  linkedin:       https://www.linkedin.com/in/akshaythorve
  instagram:      akshaythorve
  flickr:
  tumblr:
  google_plus:    https://plus.google.com/u/1/+AkshayThorveLink
  # orcid and google scholar IDs are different than standard username.
  #orcid: xyz123abc
#  gscholar: xyz123abc

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="iconside iconm-file-pdf"></i> Resume
    url: https://akshaythorve.com/files/Akshay-Thorve-Resume.pdf
    external: true
  - title: <i class="iconside iconm-linkedin2"></i> LinkedIn
    url: https://www.linkedin.com/in/akshaythorve
    external: true
  - title: <i class="iconside iconm-github2"></i> GitHub
    url: https://github.com/thorveakshay/
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  # - title: <i class="iconside iconm-feed2"></i> Feed
  #   url: /feed.xml

# Google Custom Search:
google_search: AIzaSyDC_xqGf8YdQAyVsAE4JtKFO0SvjGJX574

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
twitter_widget_id: 981788532019576832

# Giscus comments (GitHub Discussions-based)
giscus:
  repo: thorveakshay/thorveakshay.github.io
  repo-id: MDEwOlJlcG9zaXRvcnkxMjgyNjQ5Nzg=
  category: Comments
  category-id: DIC_kwDOB6UrEs4C05TG
  mapping: pathname
  strict: 0
  reactions-enabled: 0
  emit-metadata: 0
  input-position: bottom
  theme: light
  lang: en
  loading: lazy

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc

#### For dummy website only - remove if you wish ####
github_repo: https://github.com/thorveakshay
version: 1.1.1
## END ##
